export const languages = {
  es: 'Español',
  en: 'English',
};

export const defaultLang = 'es';

export const ui = {
  es: {
    'nav.home': 'Inicio',
    'nav.projects': 'Proyectos',
    'nav.blog': 'Blog',
    'nav.links': 'Enlaces',
    'header.language': 'Idioma',
    'header.spanish': 'Español',
    'header.english': 'Inglés',
    'home.greeting': '👋 Hola soy',
    'home.name': 'Edgar Chambilla',
    'home.role': 'Desarrollador Full Stack',
    'home.description': 'Estudiante de <strong>Ciencias de la Computación</strong> en UTEC. Apasionado por el <strong>Machine Learning</strong> y la <strong>Arquitectura en la Nube</strong>.',
    'home.additional': 'He desarrollado aplicaciones web y móviles y me encanta la metodología startup.',
    'home.buttons.linkedin': 'LinkedIn',
    'home.buttons.github': 'GitHub',
    'home.buttons.instagram': 'Instagram',
    'projects.title': 'Proyectos',
    'projects.subtitle': 'Algunos de mis trabajos más recientes',
    'projects.viewProject': 'Ver Proyecto',
    'projects.viewCode': 'Ver Código',
    'projects.technologies': 'Tecnologías',
    'footer.rights': 'Todos los derechos reservados',
    'footer.madeWith': 'Hecho con',
    'footer.by': 'por',
  },
  en: {
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.blog': 'Blog',
    'nav.links': 'Links',
    'header.language': 'Language',
    'header.spanish': 'Spanish',
    'header.english': 'English',
    'home.greeting': '👋 Hello I\'m',
    'home.name': 'Edgar Chambilla',
    'home.role': 'Full Stack developer',
    'home.description': 'Student of <strong>Computer Science</strong> at UTEC. Passionate about <strong>Machine Learning</strong> and <strong>Cloud Architecture</strong>.',
    'home.additional': 'I have developed web and mobile applications and I love the startup methodology.',
    'home.buttons.linkedin': 'LinkedIn',
    'home.buttons.github': 'GitHub',
    'home.buttons.instagram': 'Instagram',
    'projects.title': 'Projects',
    'projects.subtitle': 'Some of my most recent work',
    'projects.viewProject': 'View Project',
    'projects.viewCode': 'View Code',
    'projects.technologies': 'Technologies',
    'footer.rights': 'All rights reserved',
    'footer.madeWith': 'Made with',
    'footer.by': 'by',
  },
} as const;